### ISSUE TITLE
Actividad 4, Mapa mental, Edgar Fabian Castro Pérez

### ISSUE THREAD

**Issue by 11042002** [SistemasTecTlaxiaco/actividad-4-mapa-mental-11042002#2]
![1663775436460](https://user-images.githubusercontent.com/72110043/191551994-5d4fc740-62b8-402a-a698-f12426de873d.jpg)
![1663775436449](https://user-images.githubusercontent.com/72110043/191552008-5de62f5b-a960-424d-807c-5d7bc8bc220e.jpg)
![1663775436434](https://user-images.githubusercontent.com/72110043/191552017-cce1ee70-8328-4fe3-8eea-07ef8a8afdc5.jpg)

**Comment by Jaczibeth** [comment]
Del 20% obtuviste un 18%.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
